name = "app-hono-cloudflare-photon"
compatibility_date = "2025-04-03"
main = "virtual:photon:cloudflare:server-entry"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counter"]